"""rename department

Revision ID: 41936b64d98e
Revises: b8d6f678e87d
Create Date: 2025-06-13 01:48:10.930951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41936b64d98e'
down_revision = 'b8d6f678e87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
