"""rename address

Revision ID: 66281af6acc5
Revises: 41936b64d98e
Create Date: 2025-06-13 01:54:16.052211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66281af6acc5'
down_revision = '41936b64d98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
